spring:
  application:
    name: health-care
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${PROJECT_ID}
          location: ${LOCATION}
          model-id: gemini-2.5-flash
          chat:
            options:
              temperature: 0.7
              top-p: 0.9
              max-output-tokens: 2000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    displayRequestDuration: true
    showExtensions: true

server:
  port: 8000
secret:
  key: ${SECRET_KEY}
cloudinary:
  key: ${CLOUDINARY_API_KEY}
  secret: ${CLOUDINARY_API_SECRET}
  name: ${CLOUDINARY_NAME}